name = "utterlyterrible/roblox_luau_template"
version = "0.1.0"
license = "MIT"

[target]
environment = "roblox"

[engines]
lune = "^0.8.9"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
zune_std = { repo = "Scythe-Technology/zune-lib", rev = "d53309c08c94711aad48df5ca114bd3d0c3c8520" }

[dependencies]
t = { wally = "osyrisrblx/t", version = "^3.1.1" }
remo = { wally = "littensy/remo", version = "^1.5.2" }
reflex = { wally = "littensy/reflex", version = "^4.3.1" }
vide = { wally = "centau/vide", version = "^0.3.1" }
lapis = { wally = "nezuo/lapis", version = "^0.3.4" }