# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
stylua = "johnnymorganz/stylua@2.1.0"
selene = "kampfkarren/selene@0.28.0"
luau-lsp = "johnnymorganz/luau-lsp@1.52.0"
pesde = "pesde-pkg/pesde@0.6.2+registry.0.2.2"
rojo = "rojo-rbx/rojo@7.5.1"
darklua = "seaofvoices/darklua@0.16.0"
