local module = require("./.pesde/scythe_technology+zune_lib/0.1.0/zune_lib/std/init")
export type LinkedList<T> = module.LinkedList<T>
export type LinkedListNode<T> = module.LinkedListNode<T>
export type UDPSocket  = module.UDPSocket 
export type UDPSocketOptions  = module.UDPSocketOptions 
export type TCPServer  = module.TCPServer 
export type TCPServerOptions  = module.TCPServerOptions 
export type TCPConnection  = module.TCPConnection 
export type TCPClientOptions  = module.TCPClientOptions 
export type HTTPResponse  = module.HTTPResponse 
export type HTTPRequest  = module.HTTPRequest 
export type HTTPServeOptions  = module.HTTPServeOptions 
return module